pages:
  stage: deploy
  script:
  - mkdir .public
  - cp -r * .public
  - mv .public public
  - cd node_modules/
  - npm install
  


  artifacts:
    paths:
    - public
       tags:
    - .net
  only:
  - feature-gitpages